export const SEARCH_START = 'SEARCH_START';
export const SEARCH_STOP = 'SEARCH_STOP';
export const SEARCH_TRACK_RESULTS_MERGE = 'SEARCH_TRACK_RESULTS_MERGE';
export const SEARCH_NEXT_HREF_UPDATE = 'SEARCH_NEXT_HREF_UPDATE';
