export const PLAYLIST_FILTER_TEXT_UPDATE = 'PLAYLIST_FILTER_TEXT_UPDATE';
export const PLAYLIST_REQUEST_QUEUE_ADD = 'PLAYLIST_REQUEST_QUEUE_ADD';
export const PLAYLIST_REQUEST_QUEUE_REMOVE = 'PLAYLIST_REQUEST_QUEUE_REMOVE';
