/* Action Types */
export const USER_PROFILE_USER_FETCH_START = 'USER_PROFILE_USER_FETCH_START';
export const USER_PROFILE_USER_FETCH_STOP = 'USER_PROFILE_USER_FETCH_STOP';
export const USER_PROFILE_USER_UPDATE = 'USER_PROFILE_USER_UPDATE';
export const USER_PROFILE_USER_FAIL = 'USER_PROFILE_USER_FAIL';

export const USER_PROFILE_TRACKS_FETCH_START = 'USER_PROFILE_TRACKS_FETCH_START';
export const USER_PROFILE_TRACKS_FETCH_STOP = 'USER_PROFILE_TRACKS_FETCH_STOP';
export const USER_PROFILE_TRACKS_MERGE = 'USER_PROFILE_TRACKS_MERGE';
export const USER_PROFILE_TRACKS_FAIL = 'USER_PROFILE_TRACKS_FAIL';
export const USER_PROFILE_TRACKS_NEXT_HREF_UPDATE = 'USER_PROFILE_TRACKS_NEXT_HREF_UPDATE';

export const USER_PROFILE_STATE_RESET = 'USER_PROFILE_STATE_RESET';
