/* Action Types */
export const USER_PROFILE_STATE_CLEAR = 'USER_PROFILE_STATE_CLEAR';
export const USER_PROFILE_USER_REQUEST = 'USER_PROFILE_USER_REQUEST';
export const USER_PROFILE_USER_RECEIVED = 'USER_PROFILE_USER_RECEIVED';
export const USER_PROFILE_USER_FAILED = 'USER_PROFILE_USER_FAILED';
export const USER_PROFILE_TRACKS_REQUEST = 'USER_PROFILE_TRACKS_REQUEST';
export const USER_PROFILE_TRACKS_RECEIVED = 'USER_PROFILE_TRACKS_RECEIVED';
export const USER_PROFILE_TRACKS_FAILED = 'USER_PROFILE_TRACKS_FAILED';
