// Profiled track
export const TRACK_PROFILE_TRACK_FETCH_START = 'TRACK_PROFILE_TRACK_FETCH_START';
export const TRACK_PROFILE_TRACK_FETCH_STOP = 'TRACK_PROFILE_TRACK_FETCH_STOP';
export const TRACK_PROFILE_TRACK_UPDATE = 'TRACK_PROFILE_TRACK_UPDATE';
export const TRACK_PROFILE_TRACK_FAIL = 'TRACK_PROFILE_TRACK_FAIL';

// Comments
export const TRACK_PROFILE_COMMENTS_FETCH_START = 'TRACK_PROFILE_COMMENTS_FETCH_START';
export const TRACK_PROFILE_COMMENTS_FETCH_STOP = 'TRACK_PROFILE_COMMENTS_FETCH_STOP';
// export const TRACK_PROFILE_COMMENTS_UPDATE = 'TRACK_PROFILE_COMMENTS_UPDATE';
export const TRACK_PROFILE_COMMENTS_APPEND = 'TRACK_PROFILE_COMMENTS_APPEND';
export const TRACK_PROFILE_COMMENTS_FAIL = 'TRACK_PROFILE_COMMENTS_FAIL';
export const TRACK_PROFILE_COMMENTS_NEXT_HREF_UPDATE = 'TRACK_PROFILE_COMMENTS_NEXT_HREF_UPDATE';

export const TRACK_PROFILE_STATE_RESET = 'TRACK_PROFILE_STATE_RESET';
