export const TRACK_PROFILE_TRACK_REQUEST = 'TRACK_PROFILE_TRACK_REQUEST';
export const TRACK_PROFILE_TRACK_RECEIVE = 'TRACK_PROFILE_TRACK_RECEIVE';
export const TRACK_PROFILE_TRACK_FETCH_FAILED = 'TRACK_PROFILE_TRACK_FETCH_FAILED';
export const TRACK_PROFILE_COMMENTS_REQUEST = 'TRACK_PROFILE_COMMENTS_REQUEST';
export const TRACK_PROFILE_COMMENTS_RECEIVE = 'TRACK_PROFILE_COMMENTS_RECEIVE';
export const TRACK_PROFILE_STATE_CLEAR = 'TRACK_PROFILE_STATE_CLEAR';
