export const TRACK_REQUEST = 'TRACK_REQUEST';
export const TRACK_RECEIVE = 'TRACK_RECEIVE';
export const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
export const COMMENTS_RECEIVE = 'COMMENTS_RECEIVE';
export const TRACK_PROFILE_STATE_CLEAR = 'TRACK_PROFILE_STATE_CLEAR';
