export const STREAM_FETCH_START = 'STREAM_FETCH_START';
export const STREAM_FETCH_STOP = 'STREAM_FETCH_STOP';
export const STREAM_APPEND = 'STREAM_APPEND';
export const STREAM_NEXT_HREF_UPDATE = 'STREAM_NEXT_HREF_UPDATE';
