export const STREAM_FETCH_START = 'STREAM_FETCH_START';
export const STREAM_FETCH_STOP = 'STREAM_FETCH_STOP';
export const STREAM_MERGE = 'STREAM_MERGE';
export const STREAM_NEXT_HREF_UPDATE = 'STREAM_NEXT_HREF_UPDATE';
export const STREAM_STATE_RESET = 'STREAM_STATE_RESET';
