/* Action Types */
export const PLAY_QUEUE_SHOW = 'PLAY_QUEUE_SHOW';
export const PLAY_QUEUE_HIDE = 'PLAY_QUEUE_HIDE';
export const PLAY_QUEUE_CLEAR = 'PLAY_QUEUE_CLEAR';
export const PLAY_QUEUE_SHUFFLE_PLAY_QUEUE_UPDATE = 'PLAY_QUEUE_SHUFFLE_PLAY_QUEUE_UPDATE';
export const PLAY_QUEUE_SHUFFLE_PLAY_QUEUE_CLEAR = 'PLAY_QUEUE_SHUFFLE_PLAY_QUEUE_CLEAR';
export const PLAY_QUEUE_ACTIVE_PLAY_QUEUE_NAME_CHANGE = 'PLAY_QUEUE_ACTIVE_PLAY_QUEUE_NAME_CHANGE';
export const PLAY_QUEUE_VISIBLE_PLAY_QUEUE_NAME_CHANGE =
  'PLAY_QUEUE_VISIBLE_PLAY_QUEUE_NAME_CHANGE';
export const PLAY_QUEUE_UPDATE = 'PLAY_QUEUE_UPDATE';
export const PLAY_QUEUE_APPEND = 'PLAY_QUEUE_APPEND';
export const PLAY_QUEUE_MERGE = 'PLAY_QUEUE_MERGE';
export const PLAY_QUEUE_TRACK_REMOVE = 'PLAY_QUEUE_TRACK_REMOVE';
