/* Action Types */
export const PLAY_QUEUE_SHOW = 'PLAY_QUEUE_SHOW';
export const PLAY_QUEUE_HIDE = 'PLAY_QUEUE_HIDE';
export const PLAY_QUEUE_CLEAR = 'PLAY_QUEUE_CLEAR';
export const PLAY_QUEUE_ACTIVE_PLAY_QUEUE_UPDATE = 'PLAY_QUEUE_ACTIVE_PLAY_QUEUE_UPDATE';
export const PLAY_QUEUE_ACTIVE_PLAY_QUEUE_NAME_UPDATE = 'PLAY_QUEUE_ACTIVE_PLAY_QUEUE_NAME_UPDATE';
export const PLAY_QUEUE_TRACK_REMOVE = 'PLAY_QUEUE_TRACK_REMOVE';
