export const DROPDOWN_SEARCH_USERS_RECEIVED = 'DROPDOWN_SEARCH_USERS_RECEIVED';
export const DROPDOWN_SEARCH_TRACKS_RECEIVED = 'DROPDOWN_SEARCH_TRACKS_RECEIVED';

export const DROPDOWN_SEARCH_RESULTS_SHOW = 'DROPDOWN_SEARCH_RESULTS_SHOW';
export const DROPDOWN_SEARCH_RESULTS_HIDE = 'DROPDOWN_SEARCH_RESULTS_HIDE';
export const DROPDOWN_SEARCH_RESULTS_CLEAR = 'DROPDOWN_SEARCH_RESULTS_CLEAR';

// SAGA
export const DROPDOWN_SEARCH_REQUEST = 'DROPDOWN_SEARCH_REQUEST';
export const DROPDOWN_SEARCH_END = 'DROPDOWN_SEARCH_END';
export const DROPDOWN_SEARCH_REQUEST_FAILED = 'DROPDOWN_SEARCH_REQUEST_FAILED';
