export const START_DROPDOWN_SEARCH = 'START_DROPDOWN_SEARCH';
export const END_DROPDOWN_SEARCH = 'END_DROPDOWN_SEARCH';

export const DROPDOWN_ARTISTS_RECEIVED = 'DROPDOWN_ARTISTS_RECEIVED';
export const DROPDOWN_TRACKS_RECEIVED = 'DROPDOWN_TRACKS_RECEIVED';
export const SHOW_DROPDOWN_SEARCH_RESULTS = 'SHOW_DROPDOWN_SEARCH_RESULTS';
export const HIDE_DROPDOWN_SEARCH_RESULTS = 'HIDE_DROPDOWN_SEARCH_RESULTS';
export const CLEAR_DROPDOWN_SEARCH_RESULTS = 'CLEAR_DROPDOWN_SEARCH_RESULTS';

export const DROPDOWN_SEARCH_REQUEST = 'DROPDOWN_SEARCH_REQUEST';
export const DROPDOWN_SEARCH_RECEIVED = 'DROPDOWN_SEARCH_RECEIVED';
