export const DROPDOWN_SEARCH_USER_RESULTS_UPDATE = 'DROPDOWN_SEARCH_USER_RESULTS_UPDATE';
export const DROPDOWN_SEARCH_TRACK_RESULTS_UPDATE = 'DROPDOWN_SEARCH_TRACK_RESULTS_UPDATE';

export const DROPDOWN_SEARCH_RESULTS_SHOW = 'DROPDOWN_SEARCH_RESULTS_SHOW';
export const DROPDOWN_SEARCH_RESULTS_HIDE = 'DROPDOWN_SEARCH_RESULTS_HIDE';
export const DROPDOWN_SEARCH_RESULTS_CLEAR = 'DROPDOWN_SEARCH_RESULTS_CLEAR';

// SAGA
export const DROPDOWN_SEARCH_START = 'DROPDOWN_SEARCH_START';
export const DROPDOWN_SEARCH_STOP = 'DROPDOWN_SEARCH_STOP';
export const DROPDOWN_SEARCH_REQUEST_FAIL = 'DROPDOWN_SEARCH_REQUEST_FAIL';
