export default [
  {
    duration: 378548,
    release_day: null,
    permalink_url: 'http://soundcloud.com/chris-z-195359356/sets/asdfasdf',
    genre: null,
    permalink: 'asdfasdf',
    purchase_url: null,
    release_month: null,
    description: null,
    uri: 'https://api.soundcloud.com/playlists/332574454',
    label_name: null,
    tag_list: '',
    release_year: null,
    secret_uri: 'https://api.soundcloud.com/playlists/332574454?secret_token=s-j3fI3',
    track_count: 2,
    user_id: 250047142,
    last_modified: '2017/06/23 04:23:47 +0000',
    license: 'all-rights-reserved',
    tracks: [
      {
        kind: 'track',
        id: 309689082,
        created_at: '2017/02/26 22:16:34 +0000',
        user_id: 10494998,
        duration: 182978,
        commentable: true,
        state: 'finished',
        original_content_size: 7310216,
        last_modified: '2017/06/28 16:19:25 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: '15-luv-scars-ko',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: '1.5 -LUV SCARS K.o 1600 (Produced By Dj Plugg)',
        description: 'LUV IS RAGE 2 COMING SOON',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/309689082',
        user: {
          id: 10494998,
          kind: 'user',
          permalink: 'liluzivert',
          username: 'LIL UZI VERT',
          last_modified: '2017/06/18 02:09:13 +0000',
          uri: 'https://api.soundcloud.com/users/10494998',
          permalink_url: 'http://soundcloud.com/liluzivert',
          avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/309689082/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liluzivert/15-luv-scars-ko',
        artwork_url: 'https://i1.sndcdn.com/artworks-000209741428-67rqy2-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/eX1JIDO9LfFB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/309689082/stream',
        playback_count: 2150878,
        download_count: 0,
        favoritings_count: 288822,
        comment_count: 1340,
      },
      {
        kind: 'track',
        id: 309689103,
        created_at: '2017/02/26 22:16:41 +0000',
        user_id: 10494998,
        duration: 195570,
        commentable: true,
        state: 'finished',
        original_content_size: 7823153,
        last_modified: '2017/06/28 04:10:52 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: '15-ysl',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: '1.5 -YSL (Produced By DP Beatz)',
        description: 'LUV IS RAGE 2 COMING SOON',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/309689103',
        user: {
          id: 10494998,
          kind: 'user',
          permalink: 'liluzivert',
          username: 'LIL UZI VERT',
          last_modified: '2017/06/18 02:09:13 +0000',
          uri: 'https://api.soundcloud.com/users/10494998',
          permalink_url: 'http://soundcloud.com/liluzivert',
          avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/309689103/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liluzivert/15-ysl',
        artwork_url: 'https://i1.sndcdn.com/artworks-000209741446-wbwipl-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/CxAdXND54eyA_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/309689103/stream',
        playback_count: 1534588,
        download_count: 0,
        favoritings_count: 263797,
        comment_count: 2068,
      },
    ],
    playlist_type: null,
    id: 332574454,
    downloadable: false,
    sharing: 'public',
    secret_token: 's-j3fI3',
    created_at: '2017/06/23 04:23:47 +0000',
    release: null,
    kind: 'playlist',
    title: 'asdfasdf',
    type: null,
    purchase_title: null,
    artwork_url: null,
    ean: null,
    streamable: true,
    user: {
      permalink_url: 'http://soundcloud.com/chris-z-195359356',
      permalink: 'chris-z-195359356',
      username: 'Chris Z',
      uri: 'https://api.soundcloud.com/users/250047142',
      last_modified: '2017/05/21 05:06:57 +0000',
      id: 250047142,
      kind: 'user',
      avatar_url: 'https://i1.sndcdn.com/avatars-000314161526-79iw5r-large.jpg',
    },
    embeddable_by: 'all',
    label_id: null,
  },
  {
    duration: 602230,
    release_day: null,
    permalink_url: 'http://soundcloud.com/chris-z-195359356/sets/third',
    genre: null,
    permalink: 'third',
    purchase_url: null,
    release_month: null,
    description: null,
    uri: 'https://api.soundcloud.com/playlists/269520102',
    label_name: null,
    tag_list: '',
    release_year: null,
    secret_uri: 'https://api.soundcloud.com/playlists/269520102?secret_token=s-fIDCp',
    track_count: 3,
    user_id: 250047142,
    last_modified: '2016/10/22 16:59:45 +0000',
    license: 'all-rights-reserved',
    tracks: [
      {
        kind: 'track',
        id: 183149271,
        created_at: '2014/12/25 22:20:49 +0000',
        user_id: 72181005,
        duration: 160276,
        commentable: true,
        state: 'finished',
        original_content_size: 2563919,
        last_modified: '2017/06/27 10:08:05 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: 'kodak-black-22-no-flocking',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: 'https://itunes.apple.com/us/album/heart-of-the-projects/id953921139',
        label_id: null,
        purchase_title: null,
        genre: 'kodakblack',
        title: 'NO FLOCKING',
        description: 'Kodak Black (Prod. VinnyxProd)',
        label_name: 'Dollaz And Dealz Entertainment',
        release: '',
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/183149271',
        user: {
          id: 72181005,
          kind: 'user',
          permalink: 'kodak-black',
          username: 'Kodak Black',
          last_modified: '2017/01/02 00:01:11 +0000',
          uri: 'https://api.soundcloud.com/users/72181005',
          permalink_url: 'http://soundcloud.com/kodak-black',
          avatar_url: 'https://i1.sndcdn.com/avatars-000230469080-ka0bxj-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/183149271/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/kodak-black/kodak-black-22-no-flocking',
        artwork_url: 'https://i1.sndcdn.com/artworks-000101340067-qrw2qa-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/cvwaGFkBG7LB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/183149271/stream',
        playback_count: 20662871,
        download_count: 125,
        favoritings_count: 990648,
        comment_count: 7965,
      },
      {
        kind: 'track',
        id: 273828810,
        created_at: '2016/07/15 16:00:34 +0000',
        user_id: 71223630,
        duration: 258976,
        commentable: true,
        state: 'finished',
        original_content_size: 74557544,
        last_modified: '2017/06/27 10:08:05 +0000',
        sharing: 'public',
        tag_list: '"21 savage" "metro boomin" sizzle atlanta "savage mode" future "no heart" ocean "x bitch"',
        permalink: 'x-feat-future',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: 'X (feat. Future)',
        description: "21 Savage & Metro Boomin's collaborative album, #SAVAGEMODE available on iTunes: http://smarturl.it/SavageModeiTunes\n\nhttp://21savage.com\nhttp://twitter.com/21savage\nhttp://instagram.com/21savage\nhttp://facebook.com/21savage\nhttp://youtube.com/c/21savage",
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: 2016,
        release_month: 7,
        release_day: 14,
        original_format: 'wav',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/273828810',
        user: {
          id: 71223630,
          kind: 'user',
          permalink: '21savage',
          username: '21 Savage',
          last_modified: '2017/05/12 19:00:48 +0000',
          uri: 'https://api.soundcloud.com/users/71223630',
          permalink_url: 'http://soundcloud.com/21savage',
          avatar_url: 'https://i1.sndcdn.com/avatars-000238817849-zp5b93-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/273828810/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/21savage/x-feat-future',
        artwork_url: 'https://i1.sndcdn.com/artworks-000171597968-6ou25w-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/yJKGtvbboNfM_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/273828810/stream',
        playback_count: 15164425,
        download_count: 0,
        favoritings_count: 1297069,
        comment_count: 11492,
      },
      {
        kind: 'track',
        id: 309689082,
        created_at: '2017/02/26 22:16:34 +0000',
        user_id: 10494998,
        duration: 182978,
        commentable: true,
        state: 'finished',
        original_content_size: 7310216,
        last_modified: '2017/06/28 16:19:25 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: '15-luv-scars-ko',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: '1.5 -LUV SCARS K.o 1600 (Produced By Dj Plugg)',
        description: 'LUV IS RAGE 2 COMING SOON',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/309689082',
        user: {
          id: 10494998,
          kind: 'user',
          permalink: 'liluzivert',
          username: 'LIL UZI VERT',
          last_modified: '2017/06/18 02:09:13 +0000',
          uri: 'https://api.soundcloud.com/users/10494998',
          permalink_url: 'http://soundcloud.com/liluzivert',
          avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/309689082/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liluzivert/15-luv-scars-ko',
        artwork_url: 'https://i1.sndcdn.com/artworks-000209741428-67rqy2-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/eX1JIDO9LfFB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/309689082/stream',
        playback_count: 2150878,
        download_count: 0,
        favoritings_count: 288822,
        comment_count: 1340,
      },
    ],
    playlist_type: null,
    id: 269520102,
    downloadable: false,
    sharing: 'public',
    secret_token: 's-fIDCp',
    created_at: '2016/10/22 16:59:45 +0000',
    release: null,
    kind: 'playlist',
    title: 'third',
    type: null,
    purchase_title: null,
    artwork_url: null,
    ean: null,
    streamable: true,
    user: {
      permalink_url: 'http://soundcloud.com/chris-z-195359356',
      permalink: 'chris-z-195359356',
      username: 'Chris Z',
      uri: 'https://api.soundcloud.com/users/250047142',
      last_modified: '2017/05/21 05:06:57 +0000',
      id: 250047142,
      kind: 'user',
      avatar_url: 'https://i1.sndcdn.com/avatars-000314161526-79iw5r-large.jpg',
    },
    embeddable_by: 'all',
    label_id: null,
  },
  {
    duration: 494360,
    release_day: null,
    permalink_url: 'http://soundcloud.com/chris-z-195359356/sets/second',
    genre: null,
    permalink: 'second',
    purchase_url: null,
    release_month: null,
    description: null,
    uri: 'https://api.soundcloud.com/playlists/269520062',
    label_name: null,
    tag_list: '',
    release_year: null,
    secret_uri: 'https://api.soundcloud.com/playlists/269520062?secret_token=s-paxGD',
    track_count: 3,
    user_id: 250047142,
    last_modified: '2016/10/22 16:59:35 +0000',
    license: 'all-rights-reserved',
    tracks: [
      {
        kind: 'track',
        id: 183149271,
        created_at: '2014/12/25 22:20:49 +0000',
        user_id: 72181005,
        duration: 160276,
        commentable: true,
        state: 'finished',
        original_content_size: 2563919,
        last_modified: '2017/06/27 10:08:05 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: 'kodak-black-22-no-flocking',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: 'https://itunes.apple.com/us/album/heart-of-the-projects/id953921139',
        label_id: null,
        purchase_title: null,
        genre: 'kodakblack',
        title: 'NO FLOCKING',
        description: 'Kodak Black (Prod. VinnyxProd)',
        label_name: 'Dollaz And Dealz Entertainment',
        release: '',
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/183149271',
        user: {
          id: 72181005,
          kind: 'user',
          permalink: 'kodak-black',
          username: 'Kodak Black',
          last_modified: '2017/01/02 00:01:11 +0000',
          uri: 'https://api.soundcloud.com/users/72181005',
          permalink_url: 'http://soundcloud.com/kodak-black',
          avatar_url: 'https://i1.sndcdn.com/avatars-000230469080-ka0bxj-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/183149271/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/kodak-black/kodak-black-22-no-flocking',
        artwork_url: 'https://i1.sndcdn.com/artworks-000101340067-qrw2qa-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/cvwaGFkBG7LB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/183149271/stream',
        playback_count: 20662871,
        download_count: 125,
        favoritings_count: 990648,
        comment_count: 7965,
      },
      {
        kind: 'track',
        id: 239777850,
        created_at: '2015/12/31 02:31:44 +0000',
        user_id: 43215413,
        duration: 151106,
        commentable: true,
        state: 'finished',
        original_content_size: 6046741,
        last_modified: '2017/06/28 22:41:34 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: 'look-at-me-ft-xxxtentacion',
        streamable: true,
        embeddable_by: 'all',
        downloadable: true,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Members Only',
        title: 'XXXTENTACION - Look At Me! (Prod. ROJAS & Jimmy Duval)',
        description: 'Members Only.\n\n@rojasonthebeat\n@xxxtentacion\n@JimmyDuval',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/239777850',
        user: {
          id: 43215413,
          kind: 'user',
          permalink: 'rojasonthebeat',
          username: 'ROJAS',
          last_modified: '2017/05/22 22:32:01 +0000',
          uri: 'https://api.soundcloud.com/users/43215413',
          permalink_url: 'http://soundcloud.com/rojasonthebeat',
          avatar_url: 'https://i1.sndcdn.com/avatars-000195567451-ntzkme-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/239777850/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/rojasonthebeat/look-at-me-ft-xxxtentacion',
        artwork_url: 'https://i1.sndcdn.com/artworks-000141347538-tibbso-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/CUDv9baA5dph_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/239777850/stream',
        download_url: 'https://api.soundcloud.com/tracks/239777850/download',
        playback_count: 13862861,
        download_count: 19447,
        favoritings_count: 1075014,
        comment_count: 13995,
      },
      {
        kind: 'track',
        id: 309689082,
        created_at: '2017/02/26 22:16:34 +0000',
        user_id: 10494998,
        duration: 182978,
        commentable: true,
        state: 'finished',
        original_content_size: 7310216,
        last_modified: '2017/06/28 16:19:25 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: '15-luv-scars-ko',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: '1.5 -LUV SCARS K.o 1600 (Produced By Dj Plugg)',
        description: 'LUV IS RAGE 2 COMING SOON',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/309689082',
        user: {
          id: 10494998,
          kind: 'user',
          permalink: 'liluzivert',
          username: 'LIL UZI VERT',
          last_modified: '2017/06/18 02:09:13 +0000',
          uri: 'https://api.soundcloud.com/users/10494998',
          permalink_url: 'http://soundcloud.com/liluzivert',
          avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/309689082/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liluzivert/15-luv-scars-ko',
        artwork_url: 'https://i1.sndcdn.com/artworks-000209741428-67rqy2-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/eX1JIDO9LfFB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/309689082/stream',
        playback_count: 2150878,
        download_count: 0,
        favoritings_count: 288822,
        comment_count: 1340,
      },
    ],
    playlist_type: null,
    id: 269520062,
    downloadable: null,
    sharing: 'public',
    secret_token: 's-paxGD',
    created_at: '2016/10/22 16:59:35 +0000',
    release: null,
    kind: 'playlist',
    title: 'Second',
    type: null,
    purchase_title: null,
    artwork_url: null,
    ean: null,
    streamable: true,
    user: {
      permalink_url: 'http://soundcloud.com/chris-z-195359356',
      permalink: 'chris-z-195359356',
      username: 'Chris Z',
      uri: 'https://api.soundcloud.com/users/250047142',
      last_modified: '2017/05/21 05:06:57 +0000',
      id: 250047142,
      kind: 'user',
      avatar_url: 'https://i1.sndcdn.com/avatars-000314161526-79iw5r-large.jpg',
    },
    embeddable_by: 'all',
    label_id: null,
  },
  {
    duration: 998726,
    release_day: null,
    permalink_url: 'http://soundcloud.com/chris-z-195359356/sets/first-playlist',
    genre: null,
    permalink: 'first-playlist',
    purchase_url: null,
    release_month: null,
    description: null,
    uri: 'https://api.soundcloud.com/playlists/263317428',
    label_name: null,
    tag_list: '',
    release_year: null,
    secret_uri: 'https://api.soundcloud.com/playlists/263317428?secret_token=s-n06EX',
    track_count: 4,
    user_id: 250047142,
    last_modified: '2016/09/29 19:26:28 +0000',
    license: 'all-rights-reserved',
    tracks: [
      {
        kind: 'track',
        id: 183149271,
        created_at: '2014/12/25 22:20:49 +0000',
        user_id: 72181005,
        duration: 160276,
        commentable: true,
        state: 'finished',
        original_content_size: 2563919,
        last_modified: '2017/06/27 10:08:05 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: 'kodak-black-22-no-flocking',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: 'https://itunes.apple.com/us/album/heart-of-the-projects/id953921139',
        label_id: null,
        purchase_title: null,
        genre: 'kodakblack',
        title: 'NO FLOCKING',
        description: 'Kodak Black (Prod. VinnyxProd)',
        label_name: 'Dollaz And Dealz Entertainment',
        release: '',
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/183149271',
        user: {
          id: 72181005,
          kind: 'user',
          permalink: 'kodak-black',
          username: 'Kodak Black',
          last_modified: '2017/01/02 00:01:11 +0000',
          uri: 'https://api.soundcloud.com/users/72181005',
          permalink_url: 'http://soundcloud.com/kodak-black',
          avatar_url: 'https://i1.sndcdn.com/avatars-000230469080-ka0bxj-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/183149271/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/kodak-black/kodak-black-22-no-flocking',
        artwork_url: 'https://i1.sndcdn.com/artworks-000101340067-qrw2qa-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/cvwaGFkBG7LB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/183149271/stream',
        playback_count: 20662871,
        download_count: 125,
        favoritings_count: 990648,
        comment_count: 7965,
      },
      {
        kind: 'track',
        id: 223302802,
        created_at: '2015/09/10 23:30:58 +0000',
        user_id: 1861575,
        duration: 430120,
        commentable: true,
        state: 'finished',
        original_content_size: 75852964,
        last_modified: '2017/06/12 10:14:55 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: 'calvin-harris-disciples-how-deep-is-your-love-liva-k-remix-free-download',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: 'https://livak.bandcamp.com/track/calvin-harris-disciples-how-deep-is-your-love-liva-k-extended-remix',
        label_id: null,
        purchase_title: 'Buy on Bandcamp',
        genre: 'Nu Disco',
        title: 'Calvin Harris & Disciples - How Deep Is Your Love (Liva K Remix)',
        description: '4 Million Views - Big Support by @robin-schulz\nThank you!',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'wav',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/223302802',
        user: {
          id: 1861575,
          kind: 'user',
          permalink: 'liva-k',
          username: 'Liva K',
          last_modified: '2017/05/01 19:38:57 +0000',
          uri: 'https://api.soundcloud.com/users/1861575',
          permalink_url: 'http://soundcloud.com/liva-k',
          avatar_url: 'https://i1.sndcdn.com/avatars-000256588887-qwfvjy-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/223302802/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liva-k/calvin-harris-disciples-how-deep-is-your-love-liva-k-remix-free-download',
        artwork_url: 'https://i1.sndcdn.com/artworks-000129151693-anevqy-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/sVvX3fhZlIGs_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/223302802/stream',
        playback_count: 3381965,
        download_count: 0,
        favoritings_count: 89126,
        comment_count: 1489,
      },
      {
        kind: 'track',
        id: 257659076,
        created_at: '2016/04/06 18:56:31 +0000',
        user_id: 4614033,
        duration: 225352,
        commentable: true,
        state: 'finished',
        original_content_size: 9705940,
        last_modified: '2017/06/28 03:54:19 +0000',
        sharing: 'public',
        tag_list: 'D.R.A.M. LILYACHTY BROCCOLI GAHDAMN 1EPIC DRAM',
        permalink: 'broccoli',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: 'http://smarturl.it/BuyBroccoli',
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: 'BROCCOLI feat. Lil Yachty (Prod By. J Gramm)',
        description: 'Produced by J-Gramm \nCo-Produced by: Rogét Chahayed & Karl Rubin\n\nFrom my debut album, Big Baby D.R.A.M.:\nStream: SmartURL.it/StreamBigBabyDRAM\nBuy: SmartURL.it/BuyBigBabyDRAM\n\nwww.bigbabydram.com\nwww.twitter.com/bigbabydram\nwww.facebook.com/bigbabydram\nwww.instagram.com/bigbabydram',
        label_name: 'W.A.V.E./EMPIRE',
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: 2016,
        release_month: 3,
        release_day: 20,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/257659076',
        user: {
          id: 4614033,
          kind: 'user',
          permalink: 'bigbabydram',
          username: 'Big Baby DRAM',
          last_modified: '2017/06/21 22:34:05 +0000',
          uri: 'https://api.soundcloud.com/users/4614033',
          permalink_url: 'http://soundcloud.com/bigbabydram',
          avatar_url: 'https://i1.sndcdn.com/avatars-000275485978-slvsz5-large.jpg',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/257659076/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/bigbabydram/broccoli',
        artwork_url: 'https://i1.sndcdn.com/artworks-000156896947-3ch8k2-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/xeXS8StuaDqa_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/257659076/stream',
        playback_count: 27732638,
        download_count: 0,
        favoritings_count: 1873311,
        comment_count: 18283,
      },
      {
        kind: 'track',
        id: 309689082,
        created_at: '2017/02/26 22:16:34 +0000',
        user_id: 10494998,
        duration: 182978,
        commentable: true,
        state: 'finished',
        original_content_size: 7310216,
        last_modified: '2017/06/28 16:19:25 +0000',
        sharing: 'public',
        tag_list: '',
        permalink: '15-luv-scars-ko',
        streamable: true,
        embeddable_by: 'all',
        downloadable: false,
        purchase_url: null,
        label_id: null,
        purchase_title: null,
        genre: 'Hip-hop & Rap',
        title: '1.5 -LUV SCARS K.o 1600 (Produced By Dj Plugg)',
        description: 'LUV IS RAGE 2 COMING SOON',
        label_name: null,
        release: null,
        track_type: null,
        key_signature: null,
        isrc: null,
        video_url: null,
        bpm: null,
        release_year: null,
        release_month: null,
        release_day: null,
        original_format: 'mp3',
        license: 'all-rights-reserved',
        uri: 'https://api.soundcloud.com/tracks/309689082',
        user: {
          id: 10494998,
          kind: 'user',
          permalink: 'liluzivert',
          username: 'LIL UZI VERT',
          last_modified: '2017/06/18 02:09:13 +0000',
          uri: 'https://api.soundcloud.com/users/10494998',
          permalink_url: 'http://soundcloud.com/liluzivert',
          avatar_url: 'https://a1.sndcdn.com/images/default_avatar_large.png',
        },
        attachments_uri: 'https://api.soundcloud.com/tracks/309689082/attachments',
        user_playback_count: 1,
        user_favorite: false,
        permalink_url: 'http://soundcloud.com/liluzivert/15-luv-scars-ko',
        artwork_url: 'https://i1.sndcdn.com/artworks-000209741428-67rqy2-large.jpg',
        waveform_url: 'https://w1.sndcdn.com/eX1JIDO9LfFB_m.png',
        stream_url: 'https://api.soundcloud.com/tracks/309689082/stream',
        playback_count: 2150878,
        download_count: 0,
        favoritings_count: 288822,
        comment_count: 1340,
      },
    ],
    playlist_type: null,
    id: 263317428,
    downloadable: false,
    sharing: 'public',
    secret_token: 's-n06EX',
    created_at: '2016/09/29 19:26:28 +0000',
    release: null,
    kind: 'playlist',
    title: 'First Playlist',
    type: null,
    purchase_title: null,
    artwork_url: null,
    ean: null,
    streamable: true,
    user: {
      permalink_url: 'http://soundcloud.com/chris-z-195359356',
      permalink: 'chris-z-195359356',
      username: 'Chris Z',
      uri: 'https://api.soundcloud.com/users/250047142',
      last_modified: '2017/05/21 05:06:57 +0000',
      id: 250047142,
      kind: 'user',
      avatar_url: 'https://i1.sndcdn.com/avatars-000314161526-79iw5r-large.jpg',
    },
    embeddable_by: 'all',
    label_id: null,
  },
];
