export const USER_PLAY_QUEUES_FETCH_START = 'USER_PLAY_QUEUES_FETCH_START';
export const USER_PLAY_QUEUES_FETCH_STOP = 'USER_PLAY_QUEUES_FETCH_STOP';
export const USER_PLAY_QUEUES_MERGE = 'USER_PLAY_QUEUES_MERGE';
