export const USER_PLAYLISTS_FETCH_START = 'USER_PLAYLISTS_FETCH_START';
export const USER_PLAYLISTS_FETCH_STOP = 'USER_PLAYLISTS_FETCH_STOP';
export const USER_PLAYLISTS_MERGE = 'USER_PLAYLISTS_MERGE';
