/* Action Types */
export const USER_STATE_CLEAR = 'USER_STATE_CLEAR';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVE = 'USER_RECEIVE';
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL';
export const USER_TRACKS_REQUEST = 'USER_TRACKS_REQUEST';
export const USER_TRACKS_RECEIVE = 'USER_TRACKS_RECEIVE';
export const USER_TRACKS_FETCH_FAIL = 'USER_TRACKS_FETCH_FAIL';
