export const SEARCH_KEY_UPDATE = 'SEARCH_KEY_UPDATE';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_STOP = 'SEARCH_STOP';
export const SEARCH_TRACK_RESULTS_MERGE = 'SEARCH_TRACK_RESULTS_MERGE';
export const SEARCH_STATE_RESET = 'SEARCH_STATE_RESET';
