export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGOUT_SUCCESS = 'AUTH_USER_LOGOUT_SUCCESS';
export const AUTH_FAVORITES_SET = 'AUTH_FAVORITES_SET';
export const AUTH_SESSION_SET = 'AUTH_SESSION_SET';
export const AUTH_FAVORITES_ADD = 'AUTH_FAVORITES_ADD';
export const AUTH_FAVORITES_REMOVE = 'AUTH_FAVORITES_REMOVE';
export const OAUTH_TOKEN = 'OAUTH_TOKEN';
