export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const OAUTH_TOKEN = 'OAUTH_TOKEN';
export const SET_OAUTH_TOKEN = 'SET_OAUTH_TOKEN';
export const SET_FAVORITE_TRACK_IDS = 'SET_FAVORITE_TRACK_IDS';
