export const SEARCH_SUGGESTION_USER_RESULTS_UPDATE = 'SEARCH_SUGGESTION_USER_RESULTS_UPDATE';
export const SEARCH_SUGGESTION_TRACK_RESULTS_UPDATE = 'SEARCH_SUGGESTION_TRACK_RESULTS_UPDATE';

export const SEARCH_SUGGESTION_RESULTS_SHOW = 'SEARCH_SUGGESTION_RESULTS_SHOW';
export const SEARCH_SUGGESTION_RESULTS_HIDE = 'SEARCH_SUGGESTION_RESULTS_HIDE';
export const SEARCH_SUGGESTION_RESULTS_CLEAR = 'SEARCH_SUGGESTION_RESULTS_CLEAR';
export const SEARCH_SUGGESTION_QUERY_UPDATE = 'SEARCH_SUGGESTION_QUERY_UPDATE';

// SAGA
export const SEARCH_SUGGESTION_START = 'SEARCH_SUGGESTION_START';
export const SEARCH_SUGGESTION_STOP = 'SEARCH_SUGGESTION_STOP';
export const SEARCH_SUGGESTION_REQUEST_FAIL = 'SEARCH_SUGGESTION_REQUEST_FAIL';
