/* Action types for charts */
export const CHARTS_GENRE_CHANGE = 'CHARTS_GENRE_CHANGE';
export const CHARTS_REQUEST = 'CHARTS_REQUEST';
export const CHARTS_RECEIVE = 'CHARTS_RECEIVE';
export const CHARTS_FETCH_FAIL = 'CHARTS_FETCH_FAIL';
export const CHARTS_CLEAR = 'CHARTS_CLEAR';
export const CHARTS_SPINNER_STOP = 'CHARTS_SPINNER_STOP';
export const CHARTS_GENRE_LIST_UPDATE = 'CHARTS_GENRE_LIST_UPDATE';
