/* Action Types */
export const PLAYLIST_TOGGLE = 'PLAYLIST_TOGGLE';
export const PLAYLIST_CLEAR_QUEUE = 'PLAYLIST_CLEAR_QUEUE';
export const PLAYLIST_SHUFFLE_PLAYLIST_UPDATE = 'PLAYLIST_SHUFFLE_PLAYLIST_UPDATE';
export const PLAYLIST_SHUFFLE_PLAYLIST_CLEAR = 'PLAYLIST_SHUFFLE_PLAYLIST_CLEAR';
export const PLAYLIST_ACTIVE_PLAYLIST_NAME_CHANGE = 'PLAYLIST_ACTIVE_PLAYLIST_NAME_CHANGE';
export const PLAYLIST_VISIBLE_PLAYLIST_NAME_CHANGE = 'PLAYLIST_VISIBLE_PLAYLIST_NAME_CHANGE';
export const PLAYLIST_UPDATE = 'PLAYLIST_UPDATE';
export const PLAYLIST_APPEND = 'PLAYLIST_APPEND';
// Not sure
export const APPEND_TRACK_TO_PLAYLIST = 'APPEND_TRACK_TO_PLAYLIST';
