/* Action Types */
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST';
export const TOGGLE_PLAYLIST = 'TOGGLE_PLAYLIST';
export const CLEAR_PLAY_QUEUE = 'CLEAR_PLAY_QUEUE';
export const APPEND_TRACK_TO_PLAYLIST = 'APPEND_TRACK_TO_PLAYLIST';
export const UPDATE_SHUFFLE_PLAYLIST = 'UPDATE_SHUFFLE_PLAYLIST';
export const CLEAR_SHUFFLE_PLAYLIST = 'CLEAR_SHUFFLE_PLAYLIST';
export const CHANGE_ACTIVE_PLAYLIST_NAME = 'CHANGE_ACTIVE_PLAYLIST_NAME';
export const CHANGE_VISIBLE_PLAYLIST_NAME = 'CHANGE_VISIBLE_PLAYLIST_NAME';
