/* Action types for charts */
export const CHARTS_FETCH_START = 'CHARTS_FETCH_START';
export const CHARTS_FETCH_STOP = 'CHARTS_FETCH_STOP';
export const CHARTS_NEXT_HREF_UPDATE = 'CHARTS_NEXT_HREF_UPDATE';
export const CHARTS_GENRE_UPDATE = 'CHARTS_GENRE_UPDATE';
export const CHARTS_FETCH_FAIL = 'CHARTS_FETCH_FAIL';
export const CHARTS_STATE_RESET = 'CHARTS_STATE_RESET';
