export const PLAYLISTS_MERGE = 'PLAYLISTS_MERGE';
export const PLAYLISTS_UPDATE = 'PLAYLISTS_UPDATE';
export const PLAYLISTS_PLAYLIST_DELETE = 'PLAYLISTS_PLAYLIST_DELETE';
export const PLAYLISTS_STATE_RESET = 'PLAYLISTS_STATE_RESET';
export const PLAYLIST_TRACK_ADD = 'PLAYLIST_TRACK_ADD';
export const PLAYLIST_TRACK_REMOVE = 'PLAYLIST_TRACK_REMOVE';
