export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const NOTIFICATION_SUCCESS_CREATE = 'NOTIFICATION_SUCCESS_CREATE';
export const NOTIFICATION_WARNING_CREATE = 'NOTIFICATION_WARNING_CREATE';
export const NOTIFICATION_STATE_CLEAR = 'NOTIFICATION_STATE_CLEAR';
