/* Search Action Types */
export const FETCH_DROPDOWN_TRACKS = 'FETCH_DROPDOWN_TRACKS';
export const FETCH_DROPDOWN_ARTISTS = 'FETCH_DROPDOWN_ARTISTS';
export const SAGA_DROPDOWN_SEARCH = 'SAGA_DROPDOWN_SEARCH';
export const SAGA_SEARCH = 'SAGA_SEARCH';
export const START_SEARCH = 'START_SEARCH';
export const SEARCH_RESULTS_RECEIVED = 'SEARCH_RESULTS_RECEIVED';

// Dropdown search
export const START_DROPDOWN_SEARCH = 'START_DROPDOWN_SEARCH';
export const END_DROPDOWN_SEARCH = 'END_DROPDOWN_SEARCH';
export const DROPDOWN_ARTISTS_RECEIVED = 'DROPDOWN_ARTISTS_RECEIVED';
export const DROPDOWN_TRACKS_RECEIVED = 'DROPDOWN_TRACKS_RECEIVED';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SHOW_DROPDOWN_SEARCH_RESULTS = 'SHOW_DROPDOWN_SEARCH_RESULTS';
export const HIDE_DROPDOWN_SEARCH_RESULTS = 'HIDE_DROPDOWN_SEARCH_RESULTS';
export const CLEAR_DROPDOWN_SEARCH_RESULTS = 'CLEAR_DROPDOWN_SEARCH_RESULTS';

// Should be moved to ducks
export const TRACKS_REQUEST = 'TRACKS_REQUEST';
export const TRACKS_RECEIVE = 'TRACKS_RECEIVE';
export const TRACKS_FAILURE = 'TRACKS_FAILURE';

// Not sure where we used it.
export const LOAD_PLAYLIST = 'LOAD_PLAYLIST';
