export const defaultArtworkImageUrl = '/images/default-artwork.png';
// export const defaultArtistImageUrl = '/images/default-artist.png';
export const defaultArtistImageUrl = 'https://i1.sndcdn.com/avatars-000249624208-d5jr2v-t500x500.jpg';
export const t500x500 = 't500x500';
export const t300x300 = 't300×300';
export const crop = 'crop';
export const large = 'large';
export const t67x67 = 't67x67'; // Only on artworks
export const badge = 'badge';
export const small = 'small';
export const tiny = 'tiny';
export const mini = 'mini';
