export const FAVORITES_FETCH_START = 'FAVORITES_FETCH_START';
export const FAVORITES_FETCH_STOP = 'FAVORITES_FETCH_STOP';
export const FAVORITES_UPDATE = 'FAVORITES_UPDATE';
export const FAVORITES_APPEND = 'FAVORITES_APPEND';
export const FAVORITES_STATE_RESET = 'FAVORITES_STATE_RESET';
export const FAVORITES_NEXT_HREF_UPDATE = 'FAVORITES_NEXT_HREF_UPDATE';
