export const FAVORITES_REQUEST = 'FAVORITES_REQUEST';
export const FAVORITES_SET = 'FAVORITES_SET';
export const FAVORITES_APPEND = 'FAVORITES_APPEND';
export const FAVORITES_STATE_CLEAR = 'FAVORITES_STATE_CLEAR';
